version: '3.8'
name: 'swivel-tech-employee-manager'
services:
  dev-db: 
    container_name: 'employee-manager-dev-db'
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: employee_db
    networks:
      - thinura
  test-db: 
    container_name: 'employee-manager-test-db'
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: employee_db
    networks:
      - thinura
networks:
  thinura:
