// HTTP 2XX SUCCESFUL CODES
 const HTTP_SUCCESS_CODE = 200;
 const HTTP_RESOURCE_CREATED_CODE = 201;
 const HTTP_RESOURCE_ACCEPTED_CODE = 202;
 const HTTP_NO_CONTENT_CODE = 204;

// HTTP 4XX CLIENT ERROR
 const HTTP_BAD_REQUEST_CODE = 400;
 const HTTP_UNAUTHORIZED_CODE = 401;
 const HTTP_FORBIDDEN_CODE = 403;
 const HTTP_NOT_FOUND_CODE = 404;
 const HTTP_REQUEST_TIMEOUT_CODE = 408;

// HTTP 5XX SERVER ERROR
 const HTTP_INTERNAL_SERVER_ERROR_CODE = 500;
 const HTTP_NOT_IMPLEMENTED_CODE = 501;
 const HTTP_BAD_GATEWAY_CODE = 502;
 const HTTP_SERVICE_UNAVAILABLE = 503;
 const HTTP_GATEWAY_TIMEOUT = 504;


module.exports = {
    HTTP_SUCCESS_CODE,
    HTTP_RESOURCE_CREATED_CODE,
    HTTP_RESOURCE_ACCEPTED_CODE,
    HTTP_NO_CONTENT_CODE,

    HTTP_BAD_REQUEST_CODE,
    HTTP_UNAUTHORIZED_CODE,
    HTTP_FORBIDDEN_CODE,
    HTTP_NOT_FOUND_CODE,
    HTTP_REQUEST_TIMEOUT_CODE,

    HTTP_INTERNAL_SERVER_ERROR_CODE,
    HTTP_NOT_IMPLEMENTED_CODE,
    HTTP_BAD_GATEWAY_CODE,
    HTTP_SERVICE_UNAVAILABLE,
    HTTP_GATEWAY_TIMEOUT,
}