// HTTP 2XX SUCCESFUL CODES
export const HTTP_SUCCESS_CODE = 200;
export const HTTP_RESOURCE_CREATED_CODE = 201;
export const HTTP_RESOURCE_ACCEPTED_CODE = 202;
export const HTTP_NO_CONTENT_CODE = 204;

// HTTP 4XX CLIENT ERROR
export const HTTP_BAD_REQUEST_CODE = 400;
export const HTTP_UNAUTHORIZED_CODE = 401
export const HTTP_FORBIDDEN_CODE = 403;
export const HTTP_NOT_FOUND_CODE = 404;
export const HTTP_REQUEST_TIMEOUT_CODE = 408;

// HTTP 5XX SERVER ERROR
export const HTTP_INTERNAL_SERVER_ERROR_CODE = 500;
export const HTTP_NOT_IMPLEMENTED_CODE = 501;
export const HTTP_BAD_GATEWAY_CODE = 502;
export const HTTP_SERVICE_UNAVAILABLE_CODE = 503;
export const HTTP_GATEWAY_TIMEOUT_CODE = 504;
