import { TABLE_RENDER_TYPES } from './tableRenderTypes';
import { EMPLOYEE_LIST_EMPTY_MESSAGE, SELECT_GENDERS_DEFAULT, SELECT_GENDERS, ADD_EMPLOYEE_SUBMIT_BUTTON_TITLE, EDIT_EMPLOYEE_SUBMIT_BUTTON_TITLE, APPLICATION_META_TILE, APPLICATION_META_TILE_DESC, APPLICATION_NAME, ADD_EMPLOYEE_BUTTON_TITLE, LIST_EMPLOYEE_BUTTON_TITLE } from './applicationConstants';

export {
    APPLICATION_NAME,
    APPLICATION_META_TILE,
    APPLICATION_META_TILE_DESC,
    TABLE_RENDER_TYPES,
    ADD_EMPLOYEE_BUTTON_TITLE,
    LIST_EMPLOYEE_BUTTON_TITLE,
    ADD_EMPLOYEE_SUBMIT_BUTTON_TITLE,
    EDIT_EMPLOYEE_SUBMIT_BUTTON_TITLE,
    SELECT_GENDERS,
    SELECT_GENDERS_DEFAULT,
    EMPLOYEE_LIST_EMPTY_MESSAGE,
}